#!/usr/bin/env python3
"""
REDHAVEN AI — Universal Finding Parser
========================================
Parses all output files generated by RedHaven modules into a structured
format that the AI brain can analyze.

Supported file types:
    - Text files (one finding per line)
    - JSON files (structured data)
    - Nuclei JSONL output
    - httpx probe results

Usage:
    from ai_brain.finding_parser import FindingParser
    parser = FindingParser("/results/target.com")
    findings = parser.parse_all()
"""

import json
import os
import re
from pathlib import Path
from typing import Dict, List, Any, Optional
from dataclasses import dataclass, field


# ============================================================================
# Data Structures
# ============================================================================

@dataclass
class Finding:
    """A single security finding from any module."""
    category: str          # e.g., "xss", "ssrf", "secrets"
    severity: str          # CRITICAL, HIGH, MEDIUM, LOW, INFO
    source_file: str       # Which file it came from
    raw_data: str          # Raw line/entry
    url: str = ""          # Target URL if applicable
    parameter: str = ""    # Affected parameter
    details: Dict = field(default_factory=dict)  # Extra context


@dataclass
class ScanResults:
    """Aggregated results from all RedHaven modules."""
    target: str
    target_dir: str

    # Recon
    subdomains: List[str] = field(default_factory=list)
    alive_urls: List[str] = field(default_factory=list)
    endpoints: List[str] = field(default_factory=list)
    parameters: List[str] = field(default_factory=list)
    technologies: List[str] = field(default_factory=list)

    # Vulnerabilities
    findings: List[Finding] = field(default_factory=list)

    # Metadata
    scan_files_found: List[str] = field(default_factory=list)
    scan_files_empty: List[str] = field(default_factory=list)

    def get_by_category(self, category: str) -> List[Finding]:
        return [f for f in self.findings if f.category == category]

    def get_by_severity(self, severity: str) -> List[Finding]:
        return [f for f in self.findings if f.severity == severity]

    @property
    def critical_count(self) -> int:
        return len(self.get_by_severity("CRITICAL"))

    @property
    def high_count(self) -> int:
        return len(self.get_by_severity("HIGH"))

    @property
    def categories(self) -> List[str]:
        return sorted(set(f.category for f in self.findings))

    def summary_dict(self) -> Dict[str, Any]:
        """Compact summary suitable for LLM prompts."""
        cat_counts = {}
        for f in self.findings:
            key = f"{f.category} ({f.severity})"
            cat_counts[key] = cat_counts.get(key, 0) + 1

        return {
            "target": self.target,
            "subdomains_count": len(self.subdomains),
            "alive_urls_count": len(self.alive_urls),
            "endpoints_count": len(self.endpoints),
            "parameters_count": len(self.parameters),
            "tech_stack": self.technologies[:20],
            "total_findings": len(self.findings),
            "critical": self.critical_count,
            "high": self.high_count,
            "findings_by_category": cat_counts,
            "categories": self.categories,
        }


# ============================================================================
# File Mapping — Maps RedHaven output files to categories
# ============================================================================

FILE_MAP = {
    # Recon files
    "recon": {
        "recon/subdomains.txt": {"type": "recon", "field": "subdomains"},
        "recon/alive_subdomains.txt": {"type": "recon", "field": "subdomains"},
        "endpoints/alive_urls.txt": {"type": "recon", "field": "alive_urls"},
        "endpoints/clean_urls.txt": {"type": "recon", "field": "endpoints"},
        "endpoints/params_urls.txt": {"type": "recon", "field": "parameters"},
        "recon/web_overview.txt": {"type": "recon", "field": "technologies"},
    },

    # Vulnerability files
    "vulns": {
        "vulns/xss.txt": {"category": "xss", "severity": "MEDIUM"},
        "vulns/ssrf.txt": {"category": "ssrf", "severity": "HIGH"},
        "vulns/idor_candidates.txt": {"category": "idor", "severity": "HIGH"},
        "vulns/bypass_403.txt": {"category": "403_bypass", "severity": "HIGH"},
        "vulns/crlf.txt": {"category": "crlf", "severity": "MEDIUM"},
        "vulns/open_redirect.txt": {"category": "open_redirect", "severity": "MEDIUM"},
        "vulns/prototype_pollution.txt": {"category": "prototype_pollution", "severity": "HIGH"},
        "vulns/graphql.txt": {"category": "graphql", "severity": "HIGH"},
        "vulns/oauth.txt": {"category": "oauth", "severity": "HIGH"},
        "vulns/logic.txt": {"category": "logic", "severity": "HIGH"},
        "vulns/ratelimit.txt": {"category": "ratelimit", "severity": "MEDIUM"},
        "vulns/supply_chain.txt": {"category": "supply_chain", "severity": "HIGH"},
        "vulns/smuggling.txt": {"category": "http_smuggling", "severity": "CRITICAL"},
        "vulns/cors.txt": {"category": "cors", "severity": "MEDIUM"},
        "vulns/cache_poison.txt": {"category": "cache_poisoning", "severity": "HIGH"},
        "vulns/race_conditions.txt": {"category": "race_condition", "severity": "HIGH"},
        "vulns/websocket.txt": {"category": "websocket", "severity": "MEDIUM"},
        "vulns/bola.txt": {"category": "bola_bfla", "severity": "CRITICAL"},
        "vulns/blind_xss.txt": {"category": "blind_xss", "severity": "HIGH"},
        "vulns/postmessage.txt": {"category": "postmessage", "severity": "MEDIUM"},
        "vulns/twofa_bypass.txt": {"category": "2fa_bypass", "severity": "HIGH"},
        "vulns/nuclei_results.txt": {"category": "nuclei", "severity": "VARIES"},
    },

    # Secrets
    "secrets": {
        "secrets/js_secrets.txt": {"category": "js_secrets", "severity": "CRITICAL"},
        "secrets/tokens.txt": {"category": "tokens", "severity": "CRITICAL"},
        "secrets/api_keys.txt": {"category": "api_keys", "severity": "CRITICAL"},
        "secrets/smart_secrets.json": {"category": "smart_secrets", "severity": "CRITICAL"},
        "secrets/metadata.txt": {"category": "metadata", "severity": "MEDIUM"},
        "secrets/backup_files.txt": {"category": "backup_files", "severity": "HIGH"},
        "secrets/swagger_endpoints.txt": {"category": "swagger", "severity": "MEDIUM"},
    },
}


# ============================================================================
# Parser
# ============================================================================

class FindingParser:
    """Parse all RedHaven output files into structured findings."""

    def __init__(self, target_dir: str, max_findings: int = 500):
        self.target_dir = Path(target_dir)
        self.max_findings = max_findings
        self.target = self.target_dir.name

    def parse_all(self) -> ScanResults:
        """Parse all known output files and return structured results."""
        results = ScanResults(
            target=self.target,
            target_dir=str(self.target_dir),
        )

        # Parse recon files
        for filename, meta in FILE_MAP["recon"].items():
            filepath = self.target_dir / filename
            if filepath.exists() and filepath.stat().st_size > 0:
                lines = self._read_lines(filepath)
                field_name = meta["field"]
                current = getattr(results, field_name, [])
                current.extend(lines)
                setattr(results, field_name, current)
                results.scan_files_found.append(filename)
            else:
                results.scan_files_empty.append(filename)

        # Parse vuln files
        for filename, meta in FILE_MAP["vulns"].items():
            filepath = self.target_dir / filename
            if filepath.exists() and filepath.stat().st_size > 0:
                findings = self._parse_vuln_file(filepath, meta)
                results.findings.extend(findings)
                results.scan_files_found.append(filename)
            else:
                results.scan_files_empty.append(filename)

        # Parse secrets files
        for filename, meta in FILE_MAP["secrets"].items():
            filepath = self.target_dir / filename
            if filepath.exists() and filepath.stat().st_size > 0:
                findings = self._parse_vuln_file(filepath, meta)
                results.findings.extend(findings)
                results.scan_files_found.append(filename)
            else:
                results.scan_files_empty.append(filename)

        # Parse Nuclei JSONL if exists
        nuclei_jsonl = self.target_dir / "vulns" / "nuclei_output.jsonl"
        if nuclei_jsonl.exists():
            results.findings.extend(self._parse_nuclei_jsonl(nuclei_jsonl))
            results.scan_files_found.append("vulns/nuclei_output.jsonl")

        # Extract tech stack from web_overview
        results.technologies = self._extract_technologies(results.technologies)

        # Deduplicate
        results.subdomains = list(set(results.subdomains))
        results.alive_urls = list(set(results.alive_urls))

        # Cap findings to avoid token overload
        if len(results.findings) > self.max_findings:
            # Keep highest severity first
            sev_order = {"CRITICAL": 0, "HIGH": 1, "MEDIUM": 2, "LOW": 3, "INFO": 4, "VARIES": 2}
            results.findings.sort(key=lambda f: sev_order.get(f.severity, 5))
            results.findings = results.findings[:self.max_findings]

        return results

    def _read_lines(self, filepath: Path) -> List[str]:
        """Read non-empty lines from a file."""
        try:
            with open(filepath, 'r', encoding='utf-8', errors='ignore') as f:
                return [line.strip() for line in f if line.strip()]
        except Exception:
            return []

    def _parse_vuln_file(self, filepath: Path, meta: Dict) -> List[Finding]:
        """Parse a vulnerability/secret output file into findings."""
        findings = []
        category = meta.get("category", "unknown")
        severity = meta.get("severity", "INFO")

        # Handle JSON files
        if filepath.suffix == '.json':
            return self._parse_json_findings(filepath, category, severity)

        lines = self._read_lines(filepath)
        for line in lines:
            url = self._extract_url(line)
            param = self._extract_param(line)

            # Try to detect severity from line content (Nuclei-style)
            detected_sev = self._detect_severity(line)
            if detected_sev and severity == "VARIES":
                severity = detected_sev

            findings.append(Finding(
                category=category,
                severity=severity,
                source_file=str(filepath.relative_to(self.target_dir)),
                raw_data=line[:500],  # Truncate for safety
                url=url,
                parameter=param,
            ))

        return findings

    def _parse_json_findings(self, filepath: Path, category: str, severity: str) -> List[Finding]:
        """Parse JSON-formatted findings (like smart_secrets output)."""
        findings = []
        try:
            with open(filepath, 'r', encoding='utf-8', errors='ignore') as f:
                data = json.load(f)

            if isinstance(data, list):
                for item in data:
                    if isinstance(item, dict):
                        findings.append(Finding(
                            category=category,
                            severity=item.get("severity", severity),
                            source_file=str(filepath.relative_to(self.target_dir)),
                            raw_data=json.dumps(item)[:500],
                            url=item.get("url", item.get("file", "")),
                            parameter=item.get("name", item.get("type", "")),
                            details=item,
                        ))
            elif isinstance(data, dict):
                # Handle single object or nested structures
                for key, val in data.items():
                    if isinstance(val, list):
                        for item in val[:50]:  # Cap per key
                            findings.append(Finding(
                                category=f"{category}_{key}",
                                severity=severity,
                                source_file=str(filepath.relative_to(self.target_dir)),
                                raw_data=str(item)[:500],
                            ))
        except Exception:
            pass

        return findings

    def _parse_nuclei_jsonl(self, filepath: Path) -> List[Finding]:
        """Parse Nuclei JSONL output format."""
        findings = []
        try:
            for line in self._read_lines(filepath):
                try:
                    item = json.loads(line)
                    severity = item.get("info", {}).get("severity", "MEDIUM").upper()
                    findings.append(Finding(
                        category="nuclei",
                        severity=severity,
                        source_file="vulns/nuclei_output.jsonl",
                        raw_data=line[:500],
                        url=item.get("matched-at", item.get("host", "")),
                        parameter=item.get("template-id", ""),
                        details={
                            "template": item.get("template-id", ""),
                            "name": item.get("info", {}).get("name", ""),
                            "tags": item.get("info", {}).get("tags", []),
                        }
                    ))
                except json.JSONDecodeError:
                    continue
        except Exception:
            pass
        return findings

    def _extract_url(self, line: str) -> str:
        """Extract URL from a finding line."""
        match = re.search(r'https?://[^\s\]\"\']+', line)
        return match.group(0) if match else ""

    def _extract_param(self, line: str) -> str:
        """Extract parameter name from a finding line."""
        # Common patterns: ?param=, &param=, [param]
        match = re.search(r'[?&]([a-zA-Z_][a-zA-Z0-9_]*)=', line)
        return match.group(1) if match else ""

    def _detect_severity(self, line: str) -> Optional[str]:
        """Detect severity from line content."""
        line_lower = line.lower()
        if "critical" in line_lower:
            return "CRITICAL"
        if "high" in line_lower:
            return "HIGH"
        if "medium" in line_lower:
            return "MEDIUM"
        if "low" in line_lower:
            return "LOW"
        if "info" in line_lower:
            return "INFO"
        return None

    def _extract_technologies(self, raw_lines: List[str]) -> List[str]:
        """Extract technology names from httpx web_overview output."""
        techs = set()
        for line in raw_lines:
            # httpx format: [WordPress 6.4.2] [nginx/1.18.0] [200 OK]
            matches = re.findall(r'\[([^\]]+)\]', line)
            for m in matches:
                if m and not re.match(r'^\d{3}\s', m):  # Skip status codes
                    techs.add(m)
        return sorted(techs)[:30]

    def to_prompt_context(self, results: Optional[ScanResults] = None, max_items: int = 50) -> str:
        """
        Convert findings into a compact text format suitable for LLM prompts.
        This is the key method that bridges RedHaven data → AI analysis.
        """
        if results is None:
            results = self.parse_all()

        sections = []
        sections.append(f"TARGET: {results.target}")
        sections.append(f"TECH STACK: {', '.join(results.technologies[:15]) or 'Unknown'}")
        sections.append(f"ATTACK SURFACE: {len(results.subdomains)} subdomains, "
                       f"{len(results.alive_urls)} alive URLs, "
                       f"{len(results.parameters)} parametrized endpoints")
        sections.append("")

        # Group findings by category
        by_category = {}
        for f in results.findings:
            if f.category not in by_category:
                by_category[f.category] = []
            by_category[f.category].append(f)

        for category, items in sorted(by_category.items()):
            severity = items[0].severity if items else "?"
            sections.append(f"[{severity}] {category.upper()}: {len(items)} findings")
            for item in items[:max_items]:
                detail = item.url or item.raw_data[:120]
                if item.parameter:
                    detail = f"param={item.parameter} | {detail}"
                sections.append(f"  → {detail}")
            if len(items) > max_items:
                sections.append(f"  ... and {len(items) - max_items} more")
            sections.append("")

        return "\n".join(sections)


# ============================================================================
# CLI
# ============================================================================

if __name__ == "__main__":
    import sys

    if len(sys.argv) < 2:
        print("Usage: finding_parser.py <target_directory>")
        sys.exit(1)

    parser = FindingParser(sys.argv[1])
    results = parser.parse_all()

    print(f"\n{'='*60}")
    print(f"REDHAVEN AI — Finding Parser Results")
    print(f"{'='*60}")

    summary = results.summary_dict()
    for k, v in summary.items():
        print(f"  {k}: {v}")

    print(f"\nFiles parsed: {len(results.scan_files_found)}")
    print(f"Files empty: {len(results.scan_files_empty)}")
    print(f"\n{'='*60}")
    print("PROMPT CONTEXT PREVIEW:")
    print(f"{'='*60}")
    print(parser.to_prompt_context(results, max_items=5))
